### ISSUE TITLE
Please make it run on all still-supported LTS releases

### ISSUE THREAD

**Issue by probonopd** [NicolasGuilloux/blade-shadow-beta#33]
Please make it run on all still-supported LTS releases of distributions, not just on the latest ones. Not everyone has the latest and greatest LInux distribution version.

**Comment by NicolasGuilloux** [comment]
Hello!

Just as a reminder, but we are not the actual developers of the application but a community of people who tries to improve the app and help the developers ;)

About the LTS version, they know they should covers at least all LTS versions of Ubuntu, since it is the most popular distribution. They are working on it ;) I don't know when it will be available though.

**Comment by probonopd** [comment]
Ah, cool, thank you. 👍
