### ISSUE TITLE
R:300 on Fedora 30

### ISSUE THREAD

**Issue by mhamzahkhan** [NicolasGuilloux/blade-shadow-beta#39]
**Describe the bug**
Trying to connect to Shadow with Fedora 30, but I get an R:300 error.

**System**
 - OS: Fedora
 - OS Version: 30
 - Environment: Gnome
 - Application: AppImage
 - Application Version: Launcher: 4.7.10 / Client: 2.13.3

**Configuration**
 - The user is in input group: Yes
 - The environment uses Xorg : No, Wayland
 - VA API detects H264 ? And H265: H264 - yes, H265: No

**To Reproduce**
1. Login
2. Start Stream

**Comment by aarnoud** [comment]
Hi @mhamzahkhan, 300 means there's a decoder issue, VA driver unsupported, so please provide :

- GPU exact model / brand
- full result of `vainfo`
- check if required F30 libs are installed for shadow based on  https://github.com/NicolasGuilloux/blade-shadow-beta/issues/35

Thanks

**Comment by madorian** [comment]
libva info: VA-API version 1.2.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.2 (libva 2.2.0)
vainfo: Driver version: Mesa Gallium driver 18.3.3 for Radeon RX Vega (VEGA10, DRM 3.30.0, 5.1.15-050115-generic, LLVM 7.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc

**Comment by mhamzahkhan** [comment]
I switched Wayland off and everything started to work fine.

**Comment by changemenemo** [comment]
So,
I really want to work it out on fedora 31. 
GPU: 970 
vainfo: returns -1 since I've installed the latest 440.36 proprietary driver from nvidia.
Before under the nouveau driver I wasn't having a lot of results with vainfo but not -1.

From the result of this :+1: 
```
$ loginctl show-session 2 -p Type  
Type=x11
```

So I am under x11 apparently. I've read there: [https://wiki.archlinux.org/index.php/hardware_video_acceleration](url)
that it's through nvidia-utils that vdainfo is supposed to be working, but I don't find it anywhere on fedora. So it is the problem?

**Comment by NicolasGuilloux** [comment]
Hi.

Please do not revive a closed issue, especially when your issue is not related to the original topic. This was an issue with Wayland. 

Apparently, your vainfo is not valid, so you need to make it work using these instruction : https://nicolasguilloux.github.io/blade-shadow-beta/#vainfo

If you still experience some difficulties, please a new issue or contact us on the Discord ;) 

Good luck!
