### ISSUE TITLE
ChromeOS support (linux)

### ISSUE THREAD

**Issue by gaetandezeiraud** [NicolasGuilloux/blade-shadow-beta#44]
Hi, 
ChromeOS allow linux application now. The system use a Debian 9 VM. I see this project don't support this version. Why ? 

ChromeOS 80 planned for Debian 10 Buster Linux support. But the next year or more.
Thanks!

**Comment by NicolasGuilloux** [comment]
Hi mate !

Debian 9 is not supported because of the Glibc version to low to fit the Shadow requirements.
I don't know if the Linux application will support the ChromeOS very well as, as you said, it is a VM and VM often does not support hardware decoding abilities.

Despite all of that, I remember some users tried the adventure. So maybe visit the Linux channel of the Official Discord to ask those who did it :)
