### ISSUE TITLE
Issues for AppImage on Fedora 28

### ISSUE THREAD

**Issue by Nabellaleen** [NicolasGuilloux/blade-shadow-beta#5]
Hi,

I'm trying to use the AppImage v1.9.5 on Fedora 28, but I encountered some issues.

# About the documentation

- For NVidia Optimus card, the technology is now very well supported by standard open source drivers, so there is no need to install proprietary drivers. You just have to install VA-API drivers for the *Intel* card to make it works.
- The beta tools needs "requests" (it should be cool to provide a requirements.txt or a Pipfile), and you could provide the link to pygobject install, which allow to use GTK. Think also to explain that users using a virtualenv needs to activate global site-packages to be able to import `gi`

# AppImage

- Dependency : on Fedora 28, I have Perl 5.26.2, but I don't have version included in the core module (it should since perl 5.9 but ...). So you have to install it manually : `sudo dnf install perl-version`
- But after these dependencies installation, I have the following error when I execute the AppImage : 
```
$ ./shadowbeta-linux-x86_64.AppImage
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
Invalid version format (version required) at /tmp/.mount_shadowhBuZmu/shadow-wrapper.pl line 218, <$fh> line 1.
```

Any idea / advices ?

**Comment by NicolasGuilloux** [comment]
Hey !
Sorry, I'm late :X

- For the NVIDIA Optimus, I wasn't aware of this trick so I will just change the wrapper to warn the user if an Optimus installation is detected instead of throwing an error.
- The beta tool is a little bit left right now, as there are some tool integrated to the AppImage to do the same thing. It is not my propriority, but I'll note it, thanks :)

- Okay, I didn't know that some Linux distro do not have this included so I will try to make it native. We want the App to start with the strict minimal requirements. Thanks for the report, I'll fix that.
- The next AppImage should embed this library. It was a miss from us as it uses curl with a SSL socket. It will be fixed soon :)

**Comment by NicolasGuilloux** [comment]
I used `wget` instead of `curl`, I hope it will make less bugs.
