### ISSUE TITLE
We need Wayland support

### ISSUE THREAD

**Issue by mrwiwi** [NicolasGuilloux/blade-shadow-beta#64]
**Describe the bug**

**System**
 - OS: [e.g. Ubuntu] Fedora by default, any distro with Wayland support and..... CHROME OS !
 - OS Version: [e.g. 18.04] Any
 - Environment: [e.g. Gnome] Any Wayland supported env
 - Application: [e.g. AppImage] Beta appimage, shadowcker
 - Application Version: [e.g. 4.17] 4.14.16

**Configuration**
 - The user is in input group ? Yes (Chrome OS Linux subsystem
 - The environment uses Xorg ? nope, that's the point
 - VA API detects H264 ? And H265 ? Yes

**To Reproduce**
Steps to reproduce the behavior (chromeos) :
1. Enable Linux subsystem in settings
2. Install all prereq libs (took the list from dockerfile of shadowcker), as base system is debian
3. Start the launcher, keyring is working...
4. Stream never starts, stay in Shadow is ready indefinitely...

Just to check, vainfo is working on default terminal, appimage is starting with no issue from penguin. Just Wayland to make it work on chromebooks.

Seriously after trying many distro on my low powered lapbook air, chromeos (fydeos here) is so much snappy, and I can decode 4k 60fps on YouTube with the mojovideodecoder ! I can't do that on anything else linux or Windows (not smooth on win) !

**Screenshots**

**Additional context**

Wayland is the future, what is the issue with the shadow launcher ? Some users have opened issues before for "Shadow is ready", that issue would stay opened..

Anybody succeed in streaming on wayland ?

**Comment by mrwiwi** [comment]
Ok, seems there is no GPU acceleration on Cristiano at the moment on ChromeOS. But still, issue is opened for Linux. What are the reasons ? Input ?

**Comment by subjectdenied** [comment]
asked this myself in the discord channel already at least 2 times. never got a reply, let alone official statement. i think i will just move on, and leave shadow behind. there are alternatives maybe not coming with this "all-in-one" approach, but will allow me to use opensource clients or steam streaming (which also is possible under wayland)

**Comment by mrwiwi** [comment]
> asked this myself in the discord channel already at least 2 times. never got a reply, let alone official statement. i think i will just move on, and leave shadow behind. there are alternatives maybe not coming with this "all-in-one" approach, but will allow me to use opensource clients or steam streaming (which also is possible under wayland)

I just got back to Windows because of that, that's a shame, a browser solution like stadia could be much easier for users...

**Comment by NicolasGuilloux** [comment]
Hi there ! Sorry, I'm not very available because I'm currently moving in another flat.

### About Wayland

It needs a total revamp of the way the inputs are captured, and how the window is managed in general. I don't see it coming any soon but we can cross our fingers ;) BTW the devs told us they are currently working a lot on the Linux app on their side, cleaning up stuff and improving support. We can hope that a dev about Wayland is in the pipe.

A workaround would be to start the stream in another TTY running Xorg. A tweak that can be a life changer for people sticking with Wayland. Somebody tried but we did not see any success right now, even though it is possible.

### About ChromeOS

There is no way to make it work right now as Crostini does not support the GPU acceleration as you mentionned, ie Crostini doesn't have access to the GPU decoding pipeline. Shadow uses the VA-API, and the only way to make it work would be with OpenGL with a lot of tweaking from their side use the Crostini driver. I guess this will be not the priority.

**Comment by mrwiwi** [comment]
Thanks Nicolas ! I would have bet on the input side of things :)
Well, I stick with windows for now, but continue checking and finger crossing !

**Comment by subjectdenied** [comment]
why is this closed, when the issue obviously is not fixed at all?
