### ISSUE TITLE
Can’t activate the low bandwidth mode on Linux

### ISSUE THREAD

**Issue by changemenemo** [NicolasGuilloux/blade-shadow-beta#74]
**Describe the bug**
When I try to enable the low bandwidth mode during streaming with the upper menu, it goes directly to the step "disable low bandwidth mode"

**System**
 - OS: Fedora
 - OS Version: 32
 - Environment: gnome
 - Application: app image extracted
 - Application Version: 5.0.709

**Configuration**
 - The user is in input group ? Don't know yet
 - The environment uses Xorg ? Xorg
 - VA API detects H264 ? And H265 ? 

```
VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG4Simple            : VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
      <unknown profile>               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD

```
**To Reproduce**
No specific thing 
**Screenshots**

**Additional context**

**Comment by NicolasGuilloux** [comment]
Hi! I let you check our tutorial [here](https://nicolasguilloux.github.io/blade-shadow-beta/setup#setup-you-gpu-for-the-va-api) which explains how to understand the `vainfo`.

With what you gave us, your GPU does not support the H265/HEVC protocole. The low bandwitch option is actually using the H265 against the H264 which give better results (understand less artefacts) for the low bitrates. Since your GPU does not support it, you can't use it.

Feel free to open this issue again if you have any question. Cheers!
